### ISSUE TITLE
Set up metafacture blog with gatsby

### ISSUE THREAD

**Issue by katauber** [metafacture/metafacture-blog#1]

**Comment by acka47** [comment]
I just made it run locally and I think it looks really nice! We won't have to adjust anything wrt the UI, I think. I noticed some missing documentation though and saw some things we should add/adjust in the blog.

Documentation:
We should also cover people who set the blog up for the first time: Mentioning which node version you need, how to install gatsby, then run `npm install` before running `gatsby develop`.

Blog:
- I already adjusted some phrasing on the main page and contact page.
- I'd like to have the Twitter bird and Octocat instead or in addition to the phrases "Follow Metafacture on Twitter" and "Metafacture on GitHub"

**Comment by acka47** [comment]
Did we already agree on a URL for the blog? If we use a subdomain `blog.metafacture.org`, we'd have to obtain an SSL certificate first I think, don't we @dr0i ? Otherwise, we could use `https://metafacture.org/blog/`...

**Comment by dr0i** [comment]
re cert: yes
