### ISSUE TITLE
Lists and blockquotes should be inside the text block

### ISSUE THREAD

**Issue by katauber** [metafacture/metafacture-blog#4]
Lists, numbered lists and blockquotes should be intended and not outside the text block (see [discussion in skohub/skohub-blog](https://github.com/skohub-io/skohub-blog/pull/2)).

Functional review: @acka47 
Code review: @fsteeg

**Comment by katauber** [comment]
These changes can also be reviewed in the deployment to https://metafacture.github.io/metafacture-blog/

**Comment by acka47** [comment]
Hmm, at https://metafacture.github.io/metafacture-blog/new-beginnings/ bullet points and quotes are not indented,

**Comment by katauber** [comment]
> These changes can also be reviewed in the deployment to https://metafacture.github.io/metafacture-blog/

Sorry, that isn't correct. These are two different branches so these changes can't be reviewed on  https://metafacture.github.io/metafacture-blog/.
Please `git checkout -b 4-listsAndBlockquotes origin/4-listsAndBlockquotes` and run `gatsby develop` to review.

**Comment by acka47** [comment]
+1
